config/routes.rb
Rollitr::Application.routes.draw do
  resources :pages
  root to: "pages#index"
  resources :users
  resources :menus

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :user
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :menus
  has_many :pages
  has_secure_password validations: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in? #makes the method available in both controller and view template

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user #bang bang turns any object into a boolean value
  end

  def require_user
    if !logged_in?
      flash[:error] = 'You need to logged in to do that'
      redirect_to root_path
    end
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :require_user, except: [:show, :index]
  def index
    @menus = Menu.all
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)

    if @menu.save
      redirect_to menus_path(@menus)
    else
      render :new
    end
  end

  def show
    @menu = Menu.find(params[:id])
  end

  def edit
    @menu = Menu.find(params[:id])
  end

  def update
    @menu = Menu.find(params[:id])

    if @menu.update(menu_params)
      redirect_to menu_path(@menu)
    else
      render :edit
    end
  end


  private
    def menu_params
      params.require(:menu).permit(:menu, :hotfood, :title)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
def index
  @pages = Page.all
  @user = User.new
end

def new
  @page = Page.new
end

def create
  @page = Page.new(page_params)

  if @page.save
    AppMailer.newslette_update(@page).deliver
    flash[:notice] = "Great, you've just send out a new one"
    redirect_to page_path(@page)
  else
    render :new
  end
end

def show
  @page = Page.find(params[:id])
end

private

  def page_params
    params.require(:page).permit(:title, :name, :email)
  end

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.where(name: params[:name]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "You have logged in"
      redirect_to root_path
    else
      flash[:error] = "Please fix the error(s)"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = User.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      AppMailer.signup_confirmation(@user).deliver
      flash[:notice] = "You've registered"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = "You have updated your profile"
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Raw 'n Roll</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <%= csrf_meta_tags %>
    <link href="http://s3.amazonaws.com/codecademy-content/courses/ltp/css/shift.css" rel="stylesheet">

    <link rel="stylesheet" href="http://s3.amazonaws.com/codecademy-content/courses/ltp/css/bootstrap.css">

  </head>

  <body>
    <div id="sticky">
      <div class="nav">
        <div class="container">
          <div class="row">
            <ul class="pull-left">
              <li>
              <%= link_to "OnTheRoll", root_path, :class => 'brand' %>
              </li>
            </ul>
            <ul class="pull-left">

              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-success dropdown-toggle" data-toggle="dropdown">
                  Menu
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                  <li><%= link_to "Food", menus_path(@menu) %></li>
                  <li><%= link_to "Newletters", menus_path(@menu) %></li>
                  <% if logged_in? %>
                  <%= link_to "Sign Out", logout_path %>
                  <% else %>
                  <%= link_to "Sign in", login_path  %>
                  <% end %>
                </ul>

              </div>

            </ul>
          </div>
        </div>
      </div>
    </div>
      <%= yield %>
  </body>

</html>

app/views/menus/_form.html.erb
<div class="basic-grey">
  <center>
  <%= form_for @menu, :html => {:multipart => true} do |f| %>
    <div class='control-group'>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.label :menu %>
      <%= f.text_area :menu, class: "food-menu" %>
    </div>
    <center><%= f.submit @menu.new_record? ? "Submit" : "Update", class: 'btn btn-success btn-lg' %></center>
  <% end %>
  </center>
</div>

app/views/menus/edit.html.erb
<%= render "form" %>

app/views/menus/index.html.erb
<div class="basic-grey">
  <% @menus.each do |menu| %>
  <h2><li><%= menu.title %></li></h2>
  <small><li>Created at<%= menu.created_at %></li></small>
  <small><li>Updated at<%= menu.updated_at %></li></small>
  <%= link_to "Look", menu_path(menu.id) %>
  <%= link_to "Create", new_menu_path %>
  <% end %>
</div>

app/views/menus/new.html.erb
<%= render "form" %>

app/views/menus/show.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-2'>
      <div class="most-grey">
        <h2></h2>
      </div>
    </div>
  <div class="row">
    <div class='col-md-8'>
      <div class="more-grey">
        <h2><%= @menu.title %></h2>
        <% if logged_in? %>
          <small><%= link_to "Edit", edit_menu_path %></small>
        <% end %>
        <p>
          <%= @menu.menu %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/pages/_form.html.erb
<div class="basic-grey">
  <center>
  <%= form_for @page, :html => {:multipart => true} do |f| %>
    <div class='control-group'>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <center><%= f.submit @page.new_record? ? "Submit" : "Update", class: 'btn btn-success btn-lg' %></center>
  <% end %>
  </center>
</div>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html>
  <body>
    <div class="jumbotron">
      <div class="container">
        <h1>ITR: On the Roll</h1>
        <p><%= link_to "Join Our Newsletter", new_user_path(@user) %></p>
        </form>
      </div>
    </div>
    <div class="neighborhood-guides">
      <div class="container        <center>
          <h2>Our specialties</h2>
              <p>Not sure what to eat? Try one of our favorites</p>
            </center><br/>
              <div class="row">
                  <div class="col-md-4">
                      <div class="thumbnail">
                        <img src="http://www.dineouthere.com/images/sushi-town-17.jpg">
                        <p><strong>The Daddy Roll</strong>. It has some fried stuff element to it, you'll like it</p>
                      </div>
                      <div class="thumbnail">
                        <img src="http://www.tulsapeople.com/in%20the%20raw5689.jpg">
                        <center><p>I think it's a <strong>Candy Roll</strong><p></center>
                      </div>
                  </div>
                   <div class="col-md-4">
                      <div class="thumbnail">
                        <img src="http://wwwdelivery.superstock.com/WI/223/1532/PreviewComp/SuperStock_1532R-55256.jpg">
                         <p>A fried roll, what else do you need to know?</p>
                      </div>
                      <div class="thumbnail">
                        <img src="http://www.travelandleisure.com/images/amexpub/0034/2887/201212-w-best-sushi-restaurants-roka-akor.jpg">
                        <p>We even semi-cook our nigiri, just to be safe</p>

                      </div>
                  </div>
                   <div class="col-md-4">
                      <div class="thumbnail">
                          <img src="http://cookingontheweekends.com/wp-content/uploads/2012/05/April13-Shrimp-Ceviche31.jpg">
                          <p>Ceviche on a martini glass, can't get more original than this!</p>
                      </div>
                  </div>
              </div>
          </h2>
      </div>
    </div>
    <div class="learn-more">
      <center><h2>Why us?</h2></center><br/>
    <div class="container">
     <div class="row">
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="http://i2.ytimg.com/vi/f0j3-nd3kJo/hqdefault.jpg">
          </div>
          <h3>Executive Chef</h3>
          <p>Leo Bandana? The Big Kahuna? Magic Leo?</p>
          <p><a href="#">See him works out</a></p>
        </div>
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="http://www.tulsagrit.com/images/full-780/in-the-raw-food-truck.jpg">
          </div>
          <h3>Multiple locations</h3>
          <p>It's a food truck! Our location changes everyday. </p>
          <p><a href="#">Learn more</a></p>
        </div>
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="http://a4.urbancdn.com/w/s/Su/M3DInxMUimhaQ0-640m.jpg">
          </div>
        </div>
        <div class="col-md-4">
          <h3>Trust our brand</h3>
          <p>It's essentially In the Raw without tipping your server :) Unless you really want to </p>
          <p><a href="#">Learn more</a></p>
        </div>
      </div>
    </div>
  </div>
  </body>
  <hr/>
  <footer class="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <center><p>developed by &#0153;Seasalt Studio</p></center>
        </div>
      </div>
    </div>
  </footer>
</html>

app/views/pages/new.html.erb
<%= render 'form' %>

app/views/pages/show.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>RailsCasts Weekly</title>
  <style type="text/css">
  body, td { color:#000000; font-size:14px; font-family:Verdana,Helvetica,Arial; }
  .divider { background-color:#555555; height:2px; }
  .episode h2 { margin-top:0; margin-bottom:8px; font-size:18px; }
  .episode p { margin:8px 0; }
  .episode img { border:solid 1px #777777; }
  .episode .duration { font-size:11px;color:#555555; }
  #footer { font-size:11px; color:#555555; }
  #footer a { color:#555555;}
  </style>
</head>
<body>
  <table width="100%" id="background" border="0" cellpadding="0" cellspacing="0">
    <tr><td align="center" valign="top">
      <table width="650" id="main" border="0" cellpadding="0" cellspacing="20">
        <tr>
          <td id="header" colspan="2">
            <a href="http://railscasts.com/"><img src="http://railscasts.com/images/railscasts_logo.png" width="423" height="56" alt="RailsCasts"></a>
          </td>
        </tr>
        <tr>
          <td class="divider" colspan="2" bgcolor="#555555" height="2"></td>
        </tr>
        <tr class="episode">
          <td>
            <a href="#"><img src="http://railscasts.com/assets/episodes/stills/310-getting-started-with-rails.png" width="200" height="125" alt="#310 Getting Started with Rails"></a>
          </td>
          <td valign="top">
            <h2>#310 Getting Started with Rails</h2>
            <p>Learning Ruby on Rails can be overwhelming, especially if you are new to programming. Here I will take you on a tour through various resources to help get started with Rails.</p>
            <p>
              <a href="#">Watch Episode</a>
              <span class="duration">(7 minutes)</span>
            </p>
          </td>
        </tr>
        <tr>
          <td class="divider" colspan="2" bgcolor="#555555" height="2"></td>
        </tr>
        <tr>
          <td id="footer" colspan="2" align="center">
            <p><a href="#">Unsubscribe</a> if you do not wish to receive these emails in the future.</p>
            <p>&copy;2011 RailsCasts</p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>

app/views/users/_form.html.erb
<div class="basic-grey">
  <center>
  <%= form_for @user, :html => {:multipart => true} do |f| %>
      <div class='control-group'>
        <h3><span><%= f.label :name %></span></h3>
        <%= f.text_field :name, class: "form-register" %>
      </div>
      <div class='control-group'>
        <h3><span><%= f.label :email %></span></h3>
        <%= f.text_field :email, class: "form-register" %>
      </div>
    <center><%= f.submit @user.new_record? ? "Sign up" : "Update", class: 'btn btn-success btn-lg' %></center>
    <% end %>
    </center>
</div>

app/views/users/edit.html.erb
<div class="third">
<%= render "form" %>
</div>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
  <body>
    <div class="jumbotron">
      <div class="container">
        <h1>ITR: On the Roll</h1>
        <form>
          <%= form_for @user, :html => {:multipart => true} do |f| %>
          <div class='control-group'>
            <h3><span><%= f.label :Newsletter %></span></h3>
            <%= f.text_field :email, class: "form-register" %>
          </div>
          <br/>
          <%= f.submit @user.new_record? ? "Sign up" : "Update", class: 'btn btn-success btn-md' %>
          <% end %>
        </form>
      </div>
    </div>
    <div class="neighborhood-guides">
      <div class="container">
        <center>
          <h2>Our specialties</h2>
              <p>Not sure what to eat? Try one of our favorites</p>
            </center><br/>
              <div class="row">
                  <div class="col-md-4">
                      <div class="thumbnail">
                        <img src="http://www.dineouthere.com/images/sushi-town-17.jpg">
                        <p><strong>The Daddy Roll</strong>. It has some fried stuff element to it, you'll like it</p>
                      </div>
                      <div class="thumbnail">
                        <img src="http://www.tulsapeople.com/in%20the%20raw5689.jpg">
                        <center><p>I think it's a <strong>Candy Roll</strong><p></center>
                      </div>
                  </div>
                   <div class="col-md-4">
                      <div class="thumbnail">
                        <img src="http://wwwdelivery.superstock.com/WI/223/1532/PreviewComp/SuperStock_1532R-55256.jpg">
                         <p>A fried roll, what else do you need to know?</p>
                      </div>
                      <div class="thumbnail">
                        <img src="http://www.travelandleisure.com/images/amexpub/0034/2887/201212-w-best-sushi-restaurants-roka-akor.jpg">
                        <p>We even semi-cook our nigiri, just to be safe</p>

                      </div>
                  </div>
                   <div class="col-md-4">
                      <div class="thumbnail">
                          <img src="http://cookingontheweekends.com/wp-content/uploads/2012/05/April13-Shrimp-Ceviche31.jpg">
                          <p>Ceviche on a martini glass, can't get more original than this!</p>
                      </div>
                  </div>
              </div>
          </h2>
      </div>
    </div>
    <div class="learn-more">
      <center><h2>Why us?</h2></center><br/>
    <div class="container">
     <div class="row">
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="http://i2.ytimg.com/vi/f0j3-nd3kJo/hqdefault.jpg">
          </div>
          <h3>Executive Chef</h3>
          <p>Leo Bandana? The Big Kahuna? Magic Leo?</p>
          <p><a href="#">See him works out</a></p>
        </div>
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="http://www.tulsagrit.com/images/full-780/in-the-raw-food-truck.jpg">
          </div>
          <h3>Multiple locations</h3>
          <p>It's a food truck! Our location changes everyday. </p>
          <p><a href="#">Learn more</a></p>
        </div>
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="http://a4.urbancdn.com/w/s/Su/M3DInxMUimhaQ0-640m.jpg">
          </div>
        </div>
        <div class="col-md-4">
          <h3>Trust our brand</h3>
          <p>It's essentially In the Raw without tipping your server :) Unless you really want to </p>
          <p><a href="#">Learn more</a></p>
        </div>
      </div>
    </div>
  </div>
  </body>
  <hr/>
  <footer class="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <center><p>developed by &#0153;Seasalt Studio</p></center>
        </div>
      </div>
    </div>
  </footer>
</html>

app/views/users/new.html.erb
<body>
  <%= render "form" %>
</body>

app/views/users/show.html.erb
o<%= @user.name %>
<%= link_to "edit", edit_user_path %>